import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import { shadcn } from "@clerk/themes";
import { QueryProvider } from "@/components/query-provider";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        theme: shadcn,
      }}
    >
      <html lang="en">
        <body
          className={`${interSans.variable} antialiased bg-neutral-50 dark:bg-neutral-950`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <QueryProvider>{children}</QueryProvider>{" "}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
